### ISSUE TITLE
Docs misunderstanding

### ISSUE THREAD

**Issue by montogeek** [davidtheclark/cosmiconfig#102]
Hi!

Docs says `Starting from process.cwd() (or some other directory defined by the searchPath argument to load())`, but the code (https://github.com/davidtheclark/cosmiconfig/blob/master/src/createExplorer.js#L98) actually does nothing at all if a search path is not provided.

From my understanding, it should use `process.cwd()` by default if no path is provided.

**Comment by sudo-suhas** [comment]
@montogeek I think you are right. `process.cwd()` is used if the second parameter to `createExplorer.load`, `configPath` is specified(resolved relative to it). Otherwise, the `searchPath` is resolved relative to `process.cwd`. But I am not entirely sure if we should update the docs or the code. Defaulting the `searchPath` to `process.cwd()` makes sense but I am wondering if we are missing some edge case scenario.

**Comment by sudo-suhas** [comment]
@davidtheclark Could you please take a look at this issue? I'd like to resolve this before releasing 4.0.

**Comment by davidtheclark** [comment]
I think defaulting `searchPath` to `process.cwd()` seems right. So `explorer.load()` is the equivalent of `explorer.load(proces.cwd())`. Let's do that, unless anyone objects.

**Comment by sudo-suhas** [comment]
Fixed and released in `cosmiconfig@4.0.0` 🎉

**Comment by montogeek** [comment]
Thanks!
