### ISSUE TITLE
Provide option for collect and merge all found configurations

### ISSUE THREAD

**Issue by one-humble-cranberry** [davidtheclark/cosmiconfig#149]
It would be useful to provide the ability to continue searching and collecting configuration files, merging them together instead of finding one and stopping.

Something like this?:
`collectAndMerge: boolean`, default: `false`

To make this a fully fledged feature it would also be great to provide two modifiers:
1. collectionFilter `( configs ) => configs`, default: `return configs`
2. mergeStrategy `( configs ) => config`, default: `configs.reduce(( config, next ) => Object.assign(config, next))`

The default order for priority of merge should probably be closest directory to furthest, first config found to last.

Like this:
```
/path/to/module/package.json { a: 1 }
/path/to/module/.modulerc { a: 2, b: 2 }
/path/to/.modulerc { a: 3, b: 3, c: 3 }
/.modulerc { a: 4, b: 4, c: 4, d: 4 }
```
```
{ a: 1, b: 2, c: 3, d: 4 }
```

This would mirror the .gitconfig pattern, where it loads the global config, and overrides it with the local directory config. Only this would be more powerful because you can collect directories in between, allowing organizational directories, etc.

**Comment by olsonpm** [comment]
I assume `.gitconfig` supplied this functionality out of a legitimate need, however I personally haven't come across the case where the added complexity is worth it.

I previously was helping with atom's prettier plugin, and editorconfig was the only integrated dependency to allow multiple merged configuration files.  It caused headaches because users would often have issues with editorconfig settings - but due to the multiple configurations along with its simpler api, we weren't able to give users the warnings they needed to solve their own issues.  This caused more issues to be filed on the prettier plugin repo.

Anyhoo, that's just my experience.

**Comment by sudo-suhas** [comment]
@olsonnpm I hear what you are saying. For me, it is 55:45 in favour of the feature. Because it would be nice to have this feature if somebody needs it. eslint is a good example of an use case. This was brought up earlier as well and the reason was not including it was that it was not clear what the logic for merging config files would be. Similar to the recent rewrite which added customisability, this could be done too.

**Comment by olsonpm** [comment]
Ah thanks - didn't realize this was brought up before.  And yeah it makes sense to me to add support given this is meant to be consumed by others.  That and the other features supported already add a good amount of complexity haha.

**Comment by chrisblossom** [comment]
I do not think this feature belongs inside `cosmiconfig`. This can get complex with different use cases very fast. I've released a module called [ex-config](https://github.com/chrisblossom/ex-config) that is used to extend/merge configs. You can see there are a decent amount of options needed for a full fledged configuration merger, and it isn't 100% feature complete.

I think a feature request that would go along with `cosmiconfig`'s goal of being low level is a `stopWhenFound: true` (default) option. If false, `cosmiconfig` would continue searching down the directory tree, returning an array of loaded config files, with index 0 equaling the first config found.

It gets a little complex when there are two configs are found at the same directory level (which is most likely a mistake). Maybe an old `./package.json` config and a new `./.prettierrc.js` config.

It might be a good idea to extract the config file discovery out into its own module that `cosmiconfig` would use internally.

**Comment by one-humble-cranberry** [comment]
I definitely agree since this is a library meant for consumption, having options is always preferable - I suggested this feature because it is one I would like to incorporate into my own projects and have a custom parser which does a lot of what `cosmiconfig` does - if I can leverage this product I would love to do so and return credit where it's due instead of needing to write my own solution.

I like the `stopWhenFound` instead of `collectAndMerge` - I think that reads a lot more cleanly, with the default being true to ensure no functionality is broken for current users.

The reason I suggested initially to have the `collectionFilter` (though I think a better name would be `filterStrategy`) and `mergeStrategy` options is to alleviate the other concerns which were raised here - the filter strategy would most likely retain all configurations by default, but could be used to weed out same directory configs (it should be handed the path to the located configuration) or other such constraints. The merge strategy alleviates some issues as found with the comment surrounding merge complexity - and also provides a good tap point for logging and providing feedback to the user (the same context for filter, such as the config real path, should be provided here as well for this purpose)

**Comment by chrisblossom** [comment]
@one-humble-cranberry you can use `cosmiconfig` today without any changes needed. I've made a very basic example of how you can accomplish this: [chrisblossom/cosmiconfig-all-example](https://github.com/chrisblossom/cosmiconfig-all-example).

**Comment by one-humble-cranberry** [comment]
Thanks @chrisblossom :) That definitely works,  but only if you don't want to merge same directory configuration which is admittedly reasonable to not want anyway.

At this point though I'm not sure I would be able to utilize this library for my current needs - it's important to configure a library rather than adapt one. If something changes about this library in the future having to update an adapter is much more risky than updating its configuration.

If you change your mind on this and would like, I would be more than happy to help with a pull request of this feature to your specifications, just let me know :)

**Comment by chrisblossom** [comment]
@one-humble-cranberry I do not make any decisions for this library, just putting my input in.

Although I'm a bit confused why'd you rather rewrite this library instead of using a 25 line function.

**Comment by davidtheclark** [comment]
Thanks @one-humble-cranberry for the suggestion.

Like when this issue was raised before, I still think that extending & merging configs should be the domain a different library. As @chrisblossom has outlined, it could work something like this:

- Use cosmiconfig to find and parse a config.
- Starting from that config's parent directory, `explorer.search()` again for another config.
- If you find another, merge it with the existing config and search again.
- Continue until you find no more configs.

I don't think cosmiconfig would have to change at all for this wrapper to work — which is a good sign that it could and probably should live in a separate library, which cosmiconfig can retain its original limited scope.

(You could also try implementing similar functionality with the existing `transform` option!)

**Comment by one-humble-cranberry** [comment]
Awesome thanks for all the replies :) So, currently the code I am using for this process is an fs statement in a for in a while - its raw and hacky but it's about 15 lines of code to do what I need. My hope in using external libraries is that they are more robust and have wider impact. I definitely understand the scope concern here, I just don't feel like writing more code than I have now to do what I need to be able to use this library - it's a cost / value thing. I will definitely use this library when the chance arises though, I like what you're doing and it's great to have a go-to.
