### ISSUE TITLE
Code injection security vulnerability at js-yaml

### ISSUE THREAD

**Issue by em0ney** [davidtheclark/cosmiconfig#183]
Hi there,

Thanks for making cosmiconfig!

You have a dependency on `js-yaml@3.13.0`. Please see this report of a High severity vulnerability in this module.

https://www.npmjs.com/advisories/813

**Comment by olsonpm** [comment]
thanks for the report.  I'll have time to take a look this weekend.

It's the second security issue we've had within a short time frame though, I'll probably check out alternative libraries while I'm at it.

**Comment by em0ney** [comment]
I might open up a PR for this one if there is a chance you can get it merged this week

**Comment by olsonpm** [comment]
if your issue is time sensitive then you should fork the repo and depend on that in the meantime.  I assume this issue will be addressed within the next couple weeks, but we can't promise anything.

**Comment by sudo-suhas** [comment]
Removing the lock file and a clean install would pull in the latest version of `js-yaml`. So for anybody who wishes to fix this issue immediately, there is no need to wait for a fix from this library(we'll do it though).

**Comment by olsonpm** [comment]
Alright, here's what I found.

js-yaml has three advisories which were raised on npm
- https://www.npmjs.com/advisories/16: published Jun 23rd, 2013
- https://www.npmjs.com/advisories/788: published Mar 21st, 2019
- https://www.npmjs.com/advisories/813: published Apr 15th, 2019

Two of them are irrelevant to cosmiconfig because the risk was
associated with [`load`](https://github.com/nodeca/js-yaml#load-string---options-).  Cosmiconfig uses [`safeLoad`](https://github.com/nodeca/js-yaml#safeload-string---options-)

However because of the existence of `load` vs `safeLoad`, and js-yaml providing the
functionality to parse js functions and regexes in `load`, I think it's safe to assume more
advisories will be raised which end up being irrelevant to Cosmiconfig.

I found two other yaml parsing libraries that seem reliable but neither support node v4

[yaml](https://www.npmjs.com/package/yaml) requires v6+ (seems more actively maintained than yaml-js)
[yaml-js](https://www.npmjs.com/package/yaml-js) requires v8+

Both libraries
- have no security advisories raised
- don't parse js functions or regexes and thus don't have a `load` vs `safeLoad` concept

Unfortunately I think we're stuck bumping js-yaml versions every time an advisory is raised for the
duration of cosmiconfig v5 which will always support node v4.  We should probably switch to
[yaml](https://www.npmjs.com/package/yaml) when we end up bumping node versions.
