### ISSUE TITLE
Plan to strip json comment automatically

### ISSUE THREAD

**Issue by 1000ch** [davidtheclark/cosmiconfig#20]
Do you have?

**Comment by TrySound** [comment]
I'm against this. Use js or yaml config type if you want to add some comments.

**Comment by davidtheclark** [comment]
Yeah, I'd rather keep the JSON strict, also.

**Comment by alawatthe** [comment]
Can this be reconsidered? I this problem came up, when looking at https://github.com/stylelint/stylelint/issues/982.
I don't see reasons not to do this:
* basically every other linter allows comments in their rc file
* it's easy to implement
* it is not breaking an existing code
* it could be a option to do it
* yaml is something completely different (so it is not an option)

**Comment by davidtheclark** [comment]
Just to be clear: you *can* use comments in your rc file, just not with JSON. You can use JS or YAML format. 

Have you checked out the `rcStrictJson` option? Does that do the trick for you?

One advantage of using strict JSON is that we can then use [parse-json](https://github.com/sindresorhus/parse-json) to parse, which has very helpful syntax error warnings.

Open to a PR demonstrating that this is a simple feature addition :)

**Comment by davidtheclark** [comment]
The more I think about this, though, the more I agree with @TrySound that it's an unnecessary feature (and we're better off not supporting unnecessary features). Other tools typically support comments in their JSON configuration because they only allow JSON configuration. The solution we settled on here was instead to parse other configuration syntaxes that *do* allow comments, if you want comments. Actually we were already planning to support other syntaxes for various reasons, so that was clearly the simplest solution to the comments-in-config problem.

Still open to a PR that can show it's a simple and painless feature addition. Just noting my thoughts.

**Comment by alawatthe** [comment]
> Open to a PR demonstrating that this is a simple feature addition :)

It would be indeed simple and it is working quite nicely with parse-json:

```js
const parseJson = require('parse-json');
const stripJsonComments = require('strip-json-comments');
const stylelintrc = parseJson(stripJsonComments(fs.readFileSync('.stylelintrc', 'utf8')));
```

> and we're better off not supporting unnecessary features

I totally agree with this. And will therefore not send a pull request. Closing :-)

**Comment by davidtheclark** [comment]
Ok. If somebody else comes along and wants to work on this we can re-open the issue. Thanks for your input.

**Comment by mcdado** [comment]
I'd like to give my two cents on this.

I use Visual Studio Code, which has awesome plugins for both eslint and styleint. If I open .eslintrc.json and in the "rules" object I add another property, as soon as I open the double quotes on a new line, IntelliSense kicks in and automatically suggests rule names.

The same does not happen if I use .eslintrc.js, or .eslint.yml. The same is mirrored for stylelint, where the JSON file gets IntelliSense, while all other formats do not.

This makes JSON the preferable format, but not having the possibility to comment them sucks.
