### ISSUE TITLE
Consider dropping require-from-string

### ISSUE THREAD

**Issue by olegskl** [davidtheclark/cosmiconfig#21]
It seems that [require-from-string](https://github.com/floatdrop/require-from-string) doesn't allow for modular configuration, i.e. it's impossible to split the configuration in multiple files and export them in `index.js`.

Is there a specific reason for using it? Perhaps a simple `require(filepath)` is better (and it also supports loading json files from node v0.5.x)?

**Comment by davidtheclark** [comment]
I also don't particularly like the require-from-string approach, so I am open to alternative ideas.

Have a look in https://github.com/davidtheclark/cosmiconfig/blob/master/lib/loadDefinedFile.js. We're reading the file, then figuring out how to parse it by passing the string through parsers. 

I suppose at line 25 we could replace that with `require(filepath)` (maybe that's the line you were already referring to?). We'd also have to do something about the usage at line 47, where we're just trying out different parsers to see what works. 

The only reason I'm not super happy with that is because it is inefficient: the file gets read twice, and isn't the `require()` read synchronous (?), whereas all the other stuff going on is async. I wonder if there's a way out of these inefficiencies.

**Comment by olegskl** [comment]
I see your point. Indeed, `require` is synchronous (but cached).

**Comment by TrySound** [comment]
Seems like we don't need to drop require-from-string
https://github.com/floatdrop/require-from-string/blob/master/test/index.js#L26-L33

**Comment by TrySound** [comment]
@davidtheclark You didn't document `format` option.

**Comment by TrySound** [comment]
@olegskl Try my [branch](https://github.com/davidtheclark/cosmiconfig/pull/22).

**Comment by olegskl** [comment]
Seems to be working fine.

**Comment by TrySound** [comment]
Cool!

**Comment by davidtheclark** [comment]
Released in 1.0.2
