### ISSUE TITLE
[Improvement] Support .dist extension.

### ISSUE THREAD

**Issue by Yivan** [davidtheclark/cosmiconfig#233]
Hello,

Thanks for this great tools.
I searched through the documentation, but it seems it is not an available feature.
Purpose of this issue is to hadle the .dist mecanism used on many tools.
It will allow developper to place a local config (excluded from git repo) which will override/replace the dist one.

I hope it makes sense. For us it will be helpfull (we use lint-staged which use cosmiconfig, and we would like developper to be able to set some custom config just on their computer).

Thanks.

**Comment by davidtheclark** [comment]
I don't understand the feature request, because I'm not sure what particular ".dist mechanism" you're referring to. I don't have experience with one myself, and a Google search comes up with a few different possibilities. It doesn't seem like `.dist` unanimously represents for the use case you describe (unless I'm just not turning up the right search results).

I'll close this issue because I don't really understand and I left it hanging so it's probably stale. Please open a new issue with more details if you think there's a good case to be made. Keep in mind that lint-staged can implement whatever it was on top of cosmiconfig — no need for cosmiconfig's own behavior to change, if you're just targeting that tool.

**Comment by Yivan** [comment]
@davidtheclark Thanks for your answer.
You are right our needs is for lint-staged, so I posted here thinking if it is added to your repo it will benefits to all packages (like lint staged) of this new feature.

Yes `.dist` is not a convention, but it is used by some of well-know CI packages.
In fact,, we have not to use such dist mecanisme if needed.
You could just modify the part of the code which is looking for config file:
```
    a myapp property in package.json
    a .myapprc.local file in JSON or YAML format => this is the new one
    a .myapprc file in JSON or YAML format
    a .myapprc.json file
    a .myapprc.yaml, .myapprc.yml, or .myapprc.js file
    a myapp.config.js file exporting a JS object
```
Same mecanism can be added if you want for json, yaml and js file, by locking somthing like .myapp.local.yaml, etc.

I opened an issue on lint staged so maybe they can handle it on their side: https://github.com/okonet/lint-staged/issues/894

Best regards.
