### ISSUE TITLE
Using external files with --config option - does it work?

### ISSUE THREAD

**Issue by steve-p-com** [davidtheclark/cosmiconfig#62]
I'm confused about how this is meant to work.

I am setting a path to an external config file with a `--config` command line argument e.g.

```
--config=/etc/path/to/config/file.conf
```

I can see this is initially working, in that it is setting a property within cosmiconfig's options variable in index.js to the correct value:

```
options.configPath = path.resolve(parsedCliArgs[options.argv]);
```

But, how are you mean to actually load that file? Because when you call the `load()` method, there's no need to specify `searchPath` (because the location is fixed), and you can't specify `configPath` (because only cosmiconfig knows what it got from the command line argument). And you have to specify one or the other, or `load()` just resolves with `null`.

I have been through the code and I can't see anywhere that actually uses the ```.configPath``` property. So even if I do something like

```
conf.load(process.cwd())
```
It's presumably just going to behave in the standard way, and ignore the --config setting. 

I must be missing something obvious!

On a probably unrelated note, putting --config aside for the moment. Why can't you just call `load()` with no arguments and have it default to `process.cwd()`?

**Comment by davidtheclark** [comment]
@steve-p-com: `load()` returns a Promise that resolves with the config contents: https://github.com/davidtheclark/cosmiconfig/blob/master/README.md#loadsearchpath-configpath

I'm having some trouble understanding your questions. Are you running into an error that you don't understand? Are there some lines of code that don't make sense to you?

> Why can't you just call load() with no arguments and have it default to process.cwd()?

That would be a feature request. I don't think it's really necessary, because you can always just pass in `process.cwd()`, right?

**Comment by steve-p-com** [comment]
> That would be a feature request. I don't think it's really necessary, because you can always just pass in process.cwd(), right?

That's clearly a matter of opinion, but it sounds like you are arguing that defaults are never required 'because you can always just pass in' a value. I think many others would agree that sensible default behaviour is quite important.

With regard to the original issue. Perhaps I wasn't clear. Suppose I have an app which successfully uses cosmiconfig to read it's configuration files using the normal structure. But now, I would like the app to optionally use a configuration file (if specified on the command line). So if it's present on the command line, the `--config filename` takes precedence. My question is, can cosmiconfig handle this without any changes to the application? It definitely parses the command line and extracts the specified filename. But it doesn't seem to do anything with it? It still loads any existing file, just like if you didn't specify `--config` at all.

**Comment by davidtheclark** [comment]
> It still loads any existing file, just like if you didn't specify --config at all.

@steve-p-com: If this is the case, that sounds like a bug. If you can specify the situation more exactly or create a failing test, we could try to debug it.

**Comment by davidtheclark** [comment]
> it sounds like you are arguing that defaults are never required 

@steve-p-com: Sorry I didn't explain myself well. I'm not sure that `process.cwd()` is a sensible default. Right now the project I use cosmiconfig for is stylelint, and would not want this default. Sounds like you would. It would be great to gather other opinions. But until I have a strong sense that a default is in fact sensible, I tend to lean towards being explicit rather than implicit.

**Comment by davidtheclark** [comment]
> But it doesn't seem to do anything with it? It still loads any existing file, just like if you didn't specify --config at all.

@steve-p-com : I think the bug you spotted is fixed by https://github.com/davidtheclark/cosmiconfig/pull/68. Please re-open if not.
