### ISSUE TITLE
enhancement: add config validation

### ISSUE THREAD

**Issue by Aladdin-ADD** [davidtheclark/cosmiconfig#99]

**Comment by sudo-suhas** [comment]
Hey @Aladdin-ADD, could you elaborate your use-case? What would be the advantage of adding this functionality to `cosmiconfig` instead of letting the client implement it themselves? If the client were to implement it, they would have the freedom to choose the validation library of their choice. Another option would be to implement a external wrapper module which would use the [`transform`](https://github.com/davidtheclark/cosmiconfig#transform) hook to perform the validation.

**Comment by Aladdin-ADD** [comment]
thanks for the quick response!

I'm considering using `cosmiconfig` in eslint (https://github.com/eslint/eslint/issues/9637). config validation is so common, so I think providing an optional implement but can be customized can be handy for users, and no harm to flexibility. you recon?

**Comment by sudo-suhas** [comment]
@davidtheclark, @azz, @okonet Do you mind sharing your opinion on this?

**Comment by davidtheclark** [comment]
I imagine this as a separate project. I think it makes sense to keep cosmiconfig strictly focused on *loading and parsing*. What you do with the parsed config is not cosmiconfig's concern. 

It would definitely be cool to have another library shared by open source projects that validates the parsed config, so each project doesn't have to implement that on its own! It might be pretty hard, though, to make something generic that will meet the different validation needs of different projects. Fun problem.

**Comment by azz** [comment]
There's already at least two really good libs for this that I'm aware of:

- [`jest-validate`](https://www.npmjs.com/package/jest-validate)
- [`joi`](https://github.com/hapijs/joi)

**Comment by sudo-suhas** [comment]
Based on feedback, we won't be developing this feature in `cosmiconfig`. Closing the issue for now.
